apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    disk: ssd
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: mongodb
    fsType: ext4
