version: '3'

services:
  app:
    image: mcr.microsoft.com/devcontainers/go:0-1.19-bullseye
    working_dir: /workspace
    volumes:
      - ../:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 8080:8080
    networks:
      - local

  prometheus:
    image: prom/prometheus:v2.43.0
    volumes:
      - ../configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - local

  grafana:
    image: grafana/grafana:9.5.1
    ports:
      - 3000:3000
    networks:
      - local

  alertmanager:
    image: prom/alertmanager:v0.25.0
    ports:
      - 9093:9093
    networks:
      - local

networks:
  local: