# Generated by Django 3.2 on 2021-06-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210627_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taginarticle',
            old_name='is_basic',
            new_name='is_main',
        ),
    ]
