apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment-replicas
  labels:
    app: mylabel-replicas
spec:
  replicas: 3
  selector:
    matchLabels:
      project: my-replicas
  template:
    metadata:
      labels:
        project: my-replicas
    spec:
      containers:
        - name: my-replicas-web
          image: ervand7/k8s_explore:simple_flask
          ports:
            - containerPort: 5000
