apiVersion: v1
kind: Pod
metadata:
  name: custom-resource-request-pod
spec:
  containers:
  - image: busybox
    command: ["dd", "if=/dev/zero", "of=/dev/null"]
    name: main
    resources:
      requests:
        example.org/custom-resource: 1000m
