apiVersion: v1
kind: Pod
metadata:
  name: qos-burstable2
spec:
  containers:
  - image: busybox
    args: ["sleep", "9999999"]
    name: main
    resources:
      limits:
        cpu: 100m
  - image: busybox
    args: ["sleep", "9999999"]
    name: sidecar
  terminationGracePeriodSeconds: 0
