apiVersion: v1
kind: Pod
metadata:
  name: qos-besteffort
spec:
  containers:
  - image: busybox
    args: ["sleep", "9999999"]
    name: main
  - image: busybox
    args: ["sleep", "9999999"]
    name: sidecar
  terminationGracePeriodSeconds: 0
