# Generated by Django 3.2 on 2021-07-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='password',
            field=models.CharField(max_length=10, null=True, verbose_name='Пароль от машины'),
        ),
        migrations.AddField(
            model_name='car',
            name='password_confirm',
            field=models.CharField(max_length=10, null=True, verbose_name='Подтверждение пароля от машины'),
        ),
    ]
