# Generated by Django 3.2 on 2021-06-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Наименование машины')),
            ],
        ),
        migrations.CreateModel(
            name='CarInShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Кастомная машина')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car', verbose_name='Car')),
            ],
        ),
        migrations.CreateModel(
            name='CarShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Наименование магазина')),
                ('car', models.ManyToManyField(related_name='shops', through='app.CarInShop', to='app.Car')),
            ],
        ),
        migrations.AddField(
            model_name='carinshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carshop', verbose_name='Shop'),
        ),
    ]
