[tool.poetry]
name = "tmp"
version = "0.1.0"
description = ""
authors = ["ervand7 <ervand7@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.0"
requests = "^2.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
