apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: mylabel
spec:
# selector - с какими подами будет работать наш деплоймент
  selector:
    matchLabels:
      project: myproject
# далее идет описание, как будет выглядеть наш под
  template:
    metadata:
# какие лейблы мы приклеиваем к подам
      labels:
        project: myproject
    spec:
      containers:
        - name: myproject-web
          image: ervand7/k8s_explore:simple_flask
          ports:
            - containerPort: 5000
