# Generated by Django 3.2 on 2021-07-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210714_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='last_login',
        ),
    ]
