# Под с двумя контейнерами, делящими между собой один volume, который монтируется
# в оба из них, но в различных путях

apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  containers:
  - image: ervand7/fortune
    name: html-generator
    volumeMounts:
    - name: html # том с названием html монтируется в /var/htdocs
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html # тот же том что и выше монтируется в /usr/share/nginx/html только для чтения
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes: # единственный том с названием html монтируется в 2 контейнера выше
  - name: html
    emptyDir: {}

