# Generated by Django 3.2 on 2021-05-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.TextField(default=''),
        ),
    ]
