# Generated by Django 3.2 on 2021-05-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='country',
        ),
    ]
