# Generated by Django 3.2 on 2021-05-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_player_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country', models.TextField(choices=[('RU', 'Россия'), ('UKR', 'Украина'), ('UK', 'Великобритания'), ('SP', 'Испания'), ('BR', 'Бразилия')], default='')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.TextField(default=''),
        ),
    ]
