# Generated by Django 3.2 on 2021-06-06 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('brand', models.TextField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('additional_info', models.TextField(null=True)),
                ('slug', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneApple',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.phone')),
                ('video_acc', models.TextField()),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='PhoneNokia',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.phone')),
                ('fm_radio', models.BooleanField()),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='PhoneSamsung',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.phone')),
                ('max_card_size', models.IntegerField()),
            ],
            bases=('phones.phone',),
        ),
    ]
