apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  type: ExternalName # обязательно этот тип
  externalName: api.somecompany.com # полное доменное имя фактической службы
  ports:
  - port: 80
