# Generated by Django 3.2 on 2021-07-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
