# Generated by Django 3.2 on 2021-07-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210712_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
