# Generated by Django 3.2 on 2021-07-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_car_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='last_login',
        ),
    ]
