# Generated by Django 3.2 on 2021-07-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_car_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
