# Generated by Django 3.2 on 2021-07-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_car_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='username',
            new_name='email',
        ),
    ]
